const INITIAL_LEADS = [
  {
    "business_name": "Quick Fix Plumbing",
    "city": "Houston",
    "state": "TX",
    "website": "http://quickfixplumbing.godaddysites.com",
    "email": "info@quickfixplumbing.com",
    "phone": "(713) 555-0147",
    "website_score": "2",
    "website_issues": "No SSL certificate (not secure), Built on basic template platform",
    "website_broken": "False",
    "load_time_seconds": "0.75",
    "mobile_friendly": "True",
    "has_ssl": "False",
    "has_contact_form": "True",
    "email_valid": "valid",
    "phone_validated": "+1 713-555-0147",
    "fb_url": "https://www.facebook.com/search/pages/?q=Quick%20Fix%20Plumbing%20Houston%20plumber",
    "fb_phone": "",
    "fb_owner": "",
    "owner_name": "",
    "owner_linkedin": "",
    "yelp_phone": "",
    "yelp_rating": "",
    "lead_quality_score": "80",
    "lead_priority": "HOT",
    "contact_confidence": "high",
    "pitch_angle": "No website - you're losing calls to competitors every day"
  },
  {
    "business_name": "Elite Plumbers Inc",
    "city": "Phoenix",
    "state": "AZ",
    "website": "",
    "email": "contact@eliteplumbers.com",
    "phone": "602-555-0193",
    "website_score": "1",
    "website_issues": "No website exists",
    "website_broken": "True",
    "load_time_seconds": "",
    "mobile_friendly": "False",
    "has_ssl": "False",
    "has_contact_form": "False",
    "email_valid": "fake",
    "phone_validated": "+1 602-555-0193",
    "fb_url": "https://www.facebook.com/search/pages/?q=Elite%20Plumbers%20Inc%20Phoenix%20plumber",
    "fb_phone": "",
    "fb_owner": "",
    "owner_name": "",
    "owner_linkedin": "",
    "yelp_phone": "",
    "yelp_rating": "",
    "lead_quality_score": "65",
    "lead_priority": "WARM",
    "contact_confidence": "medium",
    "pitch_angle": "No website - you're losing calls to competitors every day"
  },
  {
    "business_name": "Master Drain Solutions",
    "city": "Austin",
    "state": "TX",
    "website": "https://masterdrain.com",
    "email": "hello@masterdrain.com",
    "phone": "+1-512-555-0281",
    "website_score": "1",
    "website_issues": "Slow load time (5.7s), Not mobile-friendly, No contact form, Outdated design, Not a real plumbing business website",
    "website_broken": "False",
    "load_time_seconds": "5.69",
    "mobile_friendly": "False",
    "has_ssl": "True",
    "has_contact_form": "False",
    "email_valid": "valid",
    "phone_validated": "+1 512-555-0281",
    "fb_url": "https://www.facebook.com/search/pages/?q=Master%20Drain%20Solutions%20Austin%20plumber",
    "fb_phone": "",
    "fb_owner": "",
    "owner_name": "",
    "owner_linkedin": "",
    "yelp_phone": "",
    "yelp_rating": "",
    "lead_quality_score": "80",
    "lead_priority": "HOT",
    "contact_confidence": "high",
    "pitch_angle": "No website - you're losing calls to competitors every day"
  }
];
